export {default as Error} from "./Error"
export {default as HomeLayout} from "./HomeLayout"
export {default as Cockatail} from "./Cocktail"
export {default as About} from "./About"
export {default as Landing} from "./Landing"
export {default as Newslatter} from "./Newslatter"
export {default as SinglePageError} from "./SinglePageError"